on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: date > timestamp.txt

      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          if-no-files-found: error
          path: |
            timestamp.txt
